export interface PropertyData {
  id: string
  title: string
  youtubeId: string
  views: string
  price: string
  priceBreakdown: { building: string; land: string; misc: string; perTsubo: string }
  layout: string
  area: string
  landArea: string
  buildingCoverage: string
  floorAreaRatio: string
  terrain: string
  roadAccess: string
  zoning: string
  landCategory: string
  buildingCondition: string
  kitchen: { maker: string; series: string }
  bath: { maker: string; size: string }
  toilet: { maker: string; series: string }
  insulation: string
  uaValue: string
  earthquake: string
  builder: { name: string; location: string; specialty: string }
  points: string[]
}

export const properties: PropertyData[] = [
  {
    id: '10',
    title: '小さなかわいい平屋',
    youtubeId: '0gxkNh2BC0A',
    views: '99万回',
    price: '1,980万円',
    priceBreakdown: { building: '1,580万円', land: '280万円', misc: '120万円', perTsubo: '63.2万円' },
    layout: '3LDK',
    area: '25坪（82.6㎡）',
    landArea: '60坪（198㎡）',
    buildingCoverage: '60%',
    floorAreaRatio: '200%',
    terrain: '平坦地',
    roadAccess: '南側6m公道',
    zoning: '第一種住居地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'LIXIL', series: 'シエラS' },
    bath: { maker: 'TOTO', size: '1616' },
    toilet: { maker: 'TOTO', series: 'ZJ2' },
    insulation: '等級5',
    uaValue: '0.56',
    earthquake: '等級3',
    builder: { name: 'ハウスサポート', location: '鹿児島市', specialty: '平屋・ローコスト住宅' },
    points: ['コンパクトながら収納豊富', 'リビングから庭が一望', '家事動線を最短に設計', '自然素材をふんだんに使用', '将来のバリアフリー対応済み'],
  },
  {
    id: '11',
    title: '老後も安心して過ごせる最先端の平屋',
    youtubeId: 'm_ndZJfV8a0',
    views: '91万回',
    price: '2,880万円',
    priceBreakdown: { building: '2,280万円', land: '400万円', misc: '200万円', perTsubo: '71.3万円' },
    layout: '2LDK',
    area: '32坪（105.8㎡）',
    landArea: '75坪（247.5㎡）',
    buildingCoverage: '60%',
    floorAreaRatio: '200%',
    terrain: '平坦地',
    roadAccess: '東側8m公道',
    zoning: '第一種低層住居専用地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'Panasonic', series: 'ラクシーナ' },
    bath: { maker: 'LIXIL', size: '1620' },
    toilet: { maker: 'LIXIL', series: 'サティスG' },
    insulation: '等級6',
    uaValue: '0.46',
    earthquake: '等級3',
    builder: { name: 'シニアホームズ鹿児島', location: '鹿児島市', specialty: 'バリアフリー住宅' },
    points: ['全室段差ゼロのバリアフリー', '車いす対応の広い廊下', 'IoTによるスマートホーム', 'ヒートショック対策の全館空調', '太陽光+蓄電池で光熱費ゼロ'],
  },
  {
    id: '12',
    title: '完璧な間取りのお洒落で超かわいい平屋',
    youtubeId: 'YhgQSfYYUJ0',
    views: '78万回',
    price: '2,580万円',
    priceBreakdown: { building: '2,080万円', land: '350万円', misc: '150万円', perTsubo: '69.3万円' },
    layout: '3LDK',
    area: '30坪（99.2㎡）',
    landArea: '65坪（214.5㎡）',
    buildingCoverage: '60%',
    floorAreaRatio: '200%',
    terrain: '平坦地',
    roadAccess: '南側6m公道',
    zoning: '第一種住居地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'クリナップ', series: 'ステディア' },
    bath: { maker: 'TOTO', size: '1620' },
    toilet: { maker: 'TOTO', series: 'ネオレストAH' },
    insulation: '等級5',
    uaValue: '0.52',
    earthquake: '等級3',
    builder: { name: 'ナチュラルハウス工房', location: '姶良市', specialty: 'デザイン住宅' },
    points: ['回遊動線で家事効率UP', 'リビング天井高3.2mの開放感', 'ウォークインクローゼット2ヶ所', 'パントリー付きキッチン', 'ウッドデッキでアウトドアリビング'],
  },
  {
    id: '13',
    title: '超有名な一級建築家の作る天才的な平屋',
    youtubeId: 'rTceXJ2NoP4',
    views: '59万回',
    price: '4,200万円',
    priceBreakdown: { building: '3,400万円', land: '500万円', misc: '300万円', perTsubo: '89.5万円' },
    layout: '3LDK',
    area: '38坪',
    landArea: '90坪',
    buildingCoverage: '50%',
    floorAreaRatio: '100%',
    terrain: '平坦地',
    roadAccess: '南側10m公道',
    zoning: '第一種低層住居専用地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'kitchenhouse', series: 'エバルト' },
    bath: { maker: 'TOTO', size: '1624特注' },
    toilet: { maker: 'TOTO', series: 'ネオレストNX' },
    insulation: '等級6',
    uaValue: '0.40',
    earthquake: '等級3',
    builder: { name: 'アーキテクトデザインラボ', location: '鹿児島市', specialty: '建築家住宅' },
    points: ['一級建築家のオリジナルデザイン', '中庭を囲むコの字型プラン', '全開口サッシで内外一体', 'アイランドキッチンが主役のLDK', '素材にこだわった上質な空間'],
  },
  {
    id: '14',
    title: 'お値段大公開！20坪の小さな高性能平屋',
    youtubeId: 'Oz3mV-uGTH8',
    views: '59万回',
    price: '1,580万円',
    priceBreakdown: { building: '1,280万円', land: '200万円', misc: '100万円', perTsubo: '64万円' },
    layout: '2LDK',
    area: '20坪',
    landArea: '45坪',
    buildingCoverage: '60%',
    floorAreaRatio: '200%',
    terrain: '平坦地',
    roadAccess: '西側4m公道',
    zoning: '第一種住居地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'タカラスタンダード', series: 'グランディア' },
    bath: { maker: 'タカラスタンダード', size: '1216' },
    toilet: { maker: 'LIXIL', series: 'ベーシア' },
    insulation: '等級5',
    uaValue: '0.54',
    earthquake: '等級3',
    builder: { name: 'コスモホーム鹿児島', location: '鹿児島市', specialty: 'ローコスト高性能住宅' },
    points: ['20坪でも広く感じる設計の工夫', '高性能断熱で光熱費を抑制', '価格を全て公開する透明性', 'コンパクトでも収納は十分', '将来の間取り変更に対応可能'],
  },
  {
    id: '15',
    title: '完全に大人の女性に似合う平屋！',
    youtubeId: 'ocRVUPEcx90',
    views: '50万回',
    price: '2,780万円',
    priceBreakdown: { building: '2,180万円', land: '400万円', misc: '200万円', perTsubo: '68.1万円' },
    layout: '3LDK',
    area: '32坪',
    landArea: '70坪',
    buildingCoverage: '60%',
    floorAreaRatio: '200%',
    terrain: '平坦地',
    roadAccess: '南側6m公道',
    zoning: '第一種住居地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'LIXIL', series: 'リシェルSI' },
    bath: { maker: 'LIXIL', size: '1620' },
    toilet: { maker: 'LIXIL', series: 'サティスS' },
    insulation: '等級5',
    uaValue: '0.50',
    earthquake: '等級3',
    builder: { name: 'リヴェール住宅工房', location: '鹿児島市', specialty: '女性設計士の家づくり' },
    points: ['女性設計士による繊細なデザイン', 'パウダールーム付きの広い洗面', 'ウォークスルークローゼット', 'カフェのようなキッチン空間', 'プライバシーに配慮した窓計画'],
  },
  {
    id: '16',
    title: '嘘だろ...これが平屋はヤバすぎる！',
    youtubeId: 'WzSTo2M9Mug',
    views: '47万回',
    price: '3,500万円',
    priceBreakdown: { building: '2,800万円', land: '450万円', misc: '250万円', perTsubo: '66.7万円' },
    layout: '4LDK',
    area: '42坪',
    landArea: '100坪',
    buildingCoverage: '50%',
    floorAreaRatio: '100%',
    terrain: '平坦地',
    roadAccess: '南東角地',
    zoning: '第一種低層住居専用地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'Panasonic', series: 'Lクラス' },
    bath: { maker: 'TOTO', size: '1624' },
    toilet: { maker: 'TOTO', series: 'ネオレストAH' },
    insulation: '等級6',
    uaValue: '0.43',
    earthquake: '等級3',
    builder: { name: 'グランドホーム鹿児島', location: '鹿児島市', specialty: '大空間平屋' },
    points: ['42坪の大空間LDK', '天井高4mの吹き抜け風リビング', 'ビルトインガレージ付き', '全室南向きの贅沢な間取り', 'ホテルライクなマスターベッドルーム'],
  },
  {
    id: '17',
    title: '令和時代に超人気な間取りの平屋',
    youtubeId: '2KAwhfOO3uI',
    views: '47万回',
    price: '2,480万円',
    priceBreakdown: { building: '1,980万円', land: '350万円', misc: '150万円', perTsubo: '66万円' },
    layout: '3LDK',
    area: '30坪',
    landArea: '65坪',
    buildingCoverage: '60%',
    floorAreaRatio: '200%',
    terrain: '平坦地',
    roadAccess: '南側6m公道',
    zoning: '第一種住居地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'クリナップ', series: 'セントロ' },
    bath: { maker: 'Panasonic', size: '1616' },
    toilet: { maker: 'Panasonic', series: 'アラウーノS160' },
    insulation: '等級5',
    uaValue: '0.52',
    earthquake: '等級3',
    builder: { name: 'みらい住建', location: '霧島市', specialty: '注文住宅・平屋' },
    points: ['令和の定番「回遊動線」を採用', 'ランドリールーム完備', 'リビング横の畳コーナー', 'ファミリークローゼット', 'スタディコーナー付き'],
  },
  {
    id: '18',
    title: 'えっヤバすぎ！これはもはや平屋ではない。',
    youtubeId: 'P3walOjt0uE',
    views: '47万回',
    price: '3,800万円',
    priceBreakdown: { building: '3,000万円', land: '500万円', misc: '300万円', perTsubo: '66.7万円' },
    layout: '4LDK+S',
    area: '45坪',
    landArea: '110坪',
    buildingCoverage: '50%',
    floorAreaRatio: '100%',
    terrain: '平坦地',
    roadAccess: '南西角地',
    zoning: '第一種低層住居専用地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'LIXIL', series: 'リシェルSI' },
    bath: { maker: 'TOTO', size: '1624特注' },
    toilet: { maker: 'TOTO', series: 'ネオレストNX' },
    insulation: '等級6',
    uaValue: '0.38',
    earthquake: '等級3',
    builder: { name: '谷川建設', location: '長崎市', specialty: '木造住宅' },
    points: ['平屋とは思えない圧倒的スケール', 'インナーガレージ2台分', '書斎+ワークスペース完備', 'プライベートテラス付き主寝室', '全館空調で年中快適'],
  },
  {
    id: '19',
    title: '女性設計士の作るボーホーインテリアのかわいい平屋',
    youtubeId: 'npGkmEaOaI0',
    views: '44万回',
    price: '2,380万円',
    priceBreakdown: { building: '1,880万円', land: '350万円', misc: '150万円', perTsubo: '67.1万円' },
    layout: '3LDK',
    area: '28坪',
    landArea: '60坪',
    buildingCoverage: '60%',
    floorAreaRatio: '200%',
    terrain: '平坦地',
    roadAccess: '南側5m公道',
    zoning: '第一種住居地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'ウッドワン', series: 'スイージー' },
    bath: { maker: 'TOTO', size: '1616' },
    toilet: { maker: 'TOTO', series: 'ZJ2' },
    insulation: '等級5',
    uaValue: '0.54',
    earthquake: '等級3',
    builder: { name: 'ベガハウス', location: '鹿児島市', specialty: 'デザイン住宅' },
    points: ['ボーホーインテリアの統一感', 'アーチ壁がアクセント', '無垢材フローリングの温もり', 'オープン棚のおしゃれ収納', '土間玄関からつながるシューズクローク'],
  },
  {
    id: '20',
    title: 'シンプルおしゃれの小さく可愛い平屋',
    youtubeId: 'crfgrlvsaWY',
    views: '40万回',
    price: '1,880万円',
    priceBreakdown: { building: '1,480万円', land: '280万円', misc: '120万円', perTsubo: '67.3万円' },
    layout: '2LDK',
    area: '22坪',
    landArea: '50坪',
    buildingCoverage: '60%',
    floorAreaRatio: '200%',
    terrain: '平坦地',
    roadAccess: '東側4m公道',
    zoning: '第一種住居地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'LIXIL', series: 'シエラS' },
    bath: { maker: 'LIXIL', size: '1216' },
    toilet: { maker: 'LIXIL', series: 'ベーシア' },
    insulation: '等級4',
    uaValue: '0.60',
    earthquake: '等級3',
    builder: { name: '丸和建設', location: '霧島市', specialty: '注文住宅・平屋' },
    points: ['22坪のコンパクトでも十分な広さ', 'シンプルな外観デザイン', 'LDK16帖の開放感', '造作洗面台がおしゃれ', 'ローコストでも妥協しない品質'],
  },
]

// Helper to get property by ID (returns first one as fallback)
export function getPropertyById(id: string): PropertyData {
  return properties.find(p => p.id === id) || properties[0]
}
