export interface PropertyData {
  id: string
  title: string
  youtubeId: string
  views: string
  price: string
  priceBreakdown: { building: string; land: string; misc: string; perTsubo: string }
  layout: string
  area: string
  landArea: string
  buildingCoverage: string
  floorAreaRatio: string
  terrain: string
  roadAccess: string
  zoning: string
  landCategory: string
  buildingCondition: string
  kitchen: { maker: string; series: string }
  bath: { maker: string; size: string }
  toilet: { maker: string; series: string }
  insulation: string
  uaValue: string
  earthquake: string
  /**
   * v4.0: この物件が実物のモデルハウス（見学可能な家）かどうか。
   * true の場合、動画詳細ページに「この家の見学会を予約する」セクションが表示される。
   */
  isModelHouse?: boolean
  builder: {
    name: string
    location: string
    specialty: string
    description: string
    phone: string
    website: string
    established: string
    serviceArea: string
    features: string[]
  }
  points: string[]
  photos: string[]
  designerMemo: {
    name: string
    role: string
    comment: string
  }
}

export const properties: PropertyData[] = [
  {
    id: '10',
    title: '小さなかわいい平屋',
    youtubeId: '0gxkNh2BC0A',
    views: '99万回',
    price: '1,980万円',
    priceBreakdown: { building: '1,580万円', land: '280万円', misc: '120万円', perTsubo: '63.2万円' },
    layout: '3LDK',
    area: '25坪（82.6㎡）',
    landArea: '60坪（198㎡）',
    buildingCoverage: '60%',
    floorAreaRatio: '200%',
    terrain: '平坦地',
    roadAccess: '南側6m公道',
    zoning: '第一種住居地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'LIXIL', series: 'シエラS' },
    bath: { maker: 'TOTO', size: '1616' },
    toilet: { maker: 'TOTO', series: 'ZJ2' },
    insulation: '等級5',
    uaValue: '0.56',
    earthquake: '等級3',
    isModelHouse: true,
    builder: {
      name: 'ハウスサポート',
      location: '鹿児島県鹿児島市中央町10-2',
      specialty: '平屋・ローコスト住宅',
      description: '鹿児島を拠点に、手の届く価格で高品質な平屋住宅を提供。自然素材とシンプルデザインにこだわり、長く愛される家づくりを追求しています。年間施工実績50棟以上。',
      phone: '099-123-4567',
      website: 'https://example.com/house-support',
      established: '2005年',
      serviceArea: '鹿児島市・姶良市・霧島市',
      features: ['平屋専門の設計チーム', '自然素材標準仕様', 'アフターサポート充実', '土地探しからサポート'],
    },
    points: ['コンパクトながら収納豊富', 'リビングから庭が一望', '家事動線を最短に設計', '自然素材をふんだんに使用', '将来のバリアフリー対応済み'],
    photos: ['/images/properties/10-photo-1.jpg', '/images/properties/10-photo-2.jpg', '/images/properties/10-photo-3.jpg'],
    designerMemo: {
      name: '田中 真一',
      role: '設計担当',
      comment: '施主様の「小さくてもかわいい家がいい」というご要望を大切に、25坪ながらも開放感のある空間を目指しました。リビングから中庭が見える窓の配置がこだわりポイントです。自然素材の温かみを活かしつつ、将来のバリアフリー対応も見据えた設計にしています。',
    },
  },
  {
    id: '11',
    title: '老後も安心して過ごせる最先端の平屋',
    youtubeId: 'm_ndZJfV8a0',
    views: '91万回',
    price: '2,880万円',
    priceBreakdown: { building: '2,280万円', land: '400万円', misc: '200万円', perTsubo: '71.3万円' },
    layout: '2LDK',
    area: '32坪（105.8㎡）',
    landArea: '75坪（247.5㎡）',
    buildingCoverage: '60%',
    floorAreaRatio: '200%',
    terrain: '平坦地',
    roadAccess: '東側8m公道',
    zoning: '第一種低層住居専用地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'Panasonic', series: 'ラクシーナ' },
    bath: { maker: 'LIXIL', size: '1620' },
    toilet: { maker: 'LIXIL', series: 'サティスG' },
    insulation: '等級6',
    uaValue: '0.46',
    earthquake: '等級3',
    builder: {
      name: 'シニアホームズ鹿児島',
      location: '鹿児島県鹿児島市荒田2-15-8',
      specialty: 'バリアフリー住宅',
      description: '高齢者にやさしい住まいづくりのパイオニア。バリアフリー設計とIoT技術を融合させ、老後も安心して暮らせる次世代住宅を提案しています。',
      phone: '099-234-5678',
      website: 'https://example.com/senior-homes',
      established: '2010年',
      serviceArea: '鹿児島市・日置市・南さつま市',
      features: ['バリアフリー設計専門', 'IoTスマートホーム対応', '全館空調標準', '介護リフォーム実績多数'],
    },
    points: ['全室段差ゼロのバリアフリー', '車いす対応の広い廊下', 'IoTによるスマートホーム', 'ヒートショック対策の全館空調', '太陽光+蓄電池で光熱費ゼロ'],
    photos: ['/images/properties/11-photo-1.jpg', '/images/properties/11-photo-2.jpg', '/images/properties/11-photo-3.jpg'],
    designerMemo: {
      name: '佐藤 恵子',
      role: '設計主任',
      comment: '「老後も安心して暮らしたい」というご夫婦のご要望に応え、全室段差ゼロ・車いす対応の廊下幅を確保しました。IoTスマートホームシステムにより、照明やエアコンを音声で操作できます。全館空調でヒートショックの心配もありません。',
    },
  },
  {
    id: '12',
    title: '完璧な間取りのお洒落で超かわいい平屋',
    youtubeId: 'YhgQSfYYUJ0',
    views: '78万回',
    price: '2,580万円',
    priceBreakdown: { building: '2,080万円', land: '350万円', misc: '150万円', perTsubo: '69.3万円' },
    layout: '3LDK',
    area: '30坪（99.2㎡）',
    landArea: '65坪（214.5㎡）',
    buildingCoverage: '60%',
    floorAreaRatio: '200%',
    terrain: '平坦地',
    roadAccess: '南側6m公道',
    zoning: '第一種住居地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'クリナップ', series: 'ステディア' },
    bath: { maker: 'TOTO', size: '1620' },
    toilet: { maker: 'TOTO', series: 'ネオレストAH' },
    insulation: '等級5',
    uaValue: '0.52',
    earthquake: '等級3',
    builder: {
      name: 'ナチュラルハウス工房',
      location: '鹿児島県姶良市加治木町本町250',
      specialty: 'デザイン住宅',
      description: '「暮らしを楽しむ家」をコンセプトに、デザイン性と機能性を両立した注文住宅を提供。自然と調和する外観デザインと、暮らしやすい動線設計が評判です。',
      phone: '0995-62-1234',
      website: 'https://example.com/natural-house',
      established: '2008年',
      serviceArea: '姶良市・霧島市・鹿児島市',
      features: ['デザイナーズ住宅', '自然素材×モダンデザイン', '回遊動線設計', 'ウッドデッキ標準'],
    },
    points: ['回遊動線で家事効率UP', 'リビング天井高3.2mの開放感', 'ウォークインクローゼット2ヶ所', 'パントリー付きキッチン', 'ウッドデッキでアウトドアリビング'],
    photos: ['/images/properties/12-photo-1.jpg', '/images/properties/12-photo-2.jpg', '/images/properties/12-photo-3.jpg'],
    designerMemo: {
      name: '山下 健太',
      role: 'チーフデザイナー',
      comment: 'デザインの完成度にこだわりました。天井高3.2mのリビングは、実際の面積以上の開放感を生み出します。回遊動線により家事の効率が大幅にアップ。ウッドデッキを「もうひとつのリビング」として活用できるよう、室内との段差をなくしています。',
    },
  },
  {
    id: '13',
    title: '超有名な一級建築家の作る天才的な平屋',
    youtubeId: 'rTceXJ2NoP4',
    views: '59万回',
    price: '4,200万円',
    priceBreakdown: { building: '3,400万円', land: '500万円', misc: '300万円', perTsubo: '89.5万円' },
    layout: '3LDK',
    area: '38坪',
    landArea: '90坪',
    buildingCoverage: '50%',
    floorAreaRatio: '100%',
    terrain: '平坦地',
    roadAccess: '南側10m公道',
    zoning: '第一種低層住居専用地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'kitchenhouse', series: 'エバルト' },
    bath: { maker: 'TOTO', size: '1624特注' },
    toilet: { maker: 'TOTO', series: 'ネオレストNX' },
    insulation: '等級6',
    uaValue: '0.40',
    earthquake: '等級3',
    builder: {
      name: 'アーキテクトデザインラボ',
      location: '鹿児島県鹿児島市城山町1-30',
      specialty: '建築家住宅',
      description: '一級建築士が主宰するデザイン事務所。住む人の個性とライフスタイルを丁寧にヒアリングし、唯一無二の空間を設計。数々の建築賞受賞実績あり。',
      phone: '099-345-6789',
      website: 'https://example.com/architect-lab',
      established: '2003年',
      serviceArea: '鹿児島県全域・宮崎県一部',
      features: ['一級建築士設計', '建築賞受賞実績', '完全オーダーメイド', '素材へのこだわり'],
    },
    points: ['一級建築家のオリジナルデザイン', '中庭を囲むコの字型プラン', '全開口サッシで内外一体', 'アイランドキッチンが主役のLDK', '素材にこだわった上質な空間'],
    photos: ['/images/properties/13-photo-1.jpg', '/images/properties/13-photo-2.jpg', '/images/properties/13-photo-3.jpg'],
    designerMemo: {
      name: '黒田 誠',
      role: '一級建築士',
      comment: '中庭を囲むコの字型プランは、プライバシーを確保しながら自然光をたっぷり取り込む設計です。全開口サッシにより、内と外がシームレスにつながります。素材はすべて自分の目で厳選し、時間が経つほど味わいが増す空間を目指しました。',
    },
  },
  {
    id: '14',
    title: 'お値段大公開！20坪の小さな高性能平屋',
    youtubeId: 'Oz3mV-uGTH8',
    views: '59万回',
    price: '1,580万円',
    priceBreakdown: { building: '1,280万円', land: '200万円', misc: '100万円', perTsubo: '64万円' },
    layout: '2LDK',
    area: '20坪',
    landArea: '45坪',
    buildingCoverage: '60%',
    floorAreaRatio: '200%',
    terrain: '平坦地',
    roadAccess: '西側4m公道',
    zoning: '第一種住居地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'タカラスタンダード', series: 'グランディア' },
    bath: { maker: 'タカラスタンダード', size: '1216' },
    toilet: { maker: 'LIXIL', series: 'ベーシア' },
    insulation: '等級5',
    uaValue: '0.54',
    earthquake: '等級3',
    builder: {
      name: 'コスモホーム鹿児島',
      location: '鹿児島県鹿児島市紫原5-20-1',
      specialty: 'ローコスト高性能住宅',
      description: '「価格の見える家づくり」をモットーに、建築費用をすべて公開。ローコストでありながら断熱等級5以上の高性能住宅を実現する独自の仕入れネットワークが強み。',
      phone: '099-456-7890',
      website: 'https://example.com/cosmo-home',
      established: '2012年',
      serviceArea: '鹿児島市・日置市・いちき串木野市',
      features: ['価格全公開の透明性', '高性能×ローコスト', '独自仕入れネットワーク', '若い世代の家づくり応援'],
    },
    points: ['20坪でも広く感じる設計の工夫', '高性能断熱で光熱費を抑制', '価格を全て公開する透明性', 'コンパクトでも収納は十分', '将来の間取り変更に対応可能'],
    photos: ['/images/properties/14-photo-1.jpg', '/images/properties/14-photo-2.jpg', '/images/properties/14-photo-3.jpg'],
    designerMemo: {
      name: '中村 大輔',
      role: '設計担当',
      comment: '20坪という限られた面積でも、視線の抜けと天井高の工夫で広く感じる空間を作りました。コストを抑えながらも断熱性能は妥協せず、等級5を確保。将来の家族構成の変化にも対応できる可変間取りを採用しています。',
    },
  },
  {
    id: '15',
    title: '完全に大人の女性に似合う平屋！',
    youtubeId: 'ocRVUPEcx90',
    views: '50万回',
    price: '2,780万円',
    priceBreakdown: { building: '2,180万円', land: '400万円', misc: '200万円', perTsubo: '68.1万円' },
    layout: '3LDK',
    area: '32坪',
    landArea: '70坪',
    buildingCoverage: '60%',
    floorAreaRatio: '200%',
    terrain: '平坦地',
    roadAccess: '南側6m公道',
    zoning: '第一種住居地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'LIXIL', series: 'リシェルSI' },
    bath: { maker: 'LIXIL', size: '1620' },
    toilet: { maker: 'LIXIL', series: 'サティスS' },
    insulation: '等級5',
    uaValue: '0.50',
    earthquake: '等級3',
    builder: {
      name: 'リヴェール住宅工房',
      location: '鹿児島県鹿児島市武岡3-8-12',
      specialty: '女性設計士の家づくり',
      description: '女性設計士が中心となり、女性目線の暮らしやすさを追求した住宅を設計。キッチン・収納・洗面など水まわりの使い勝手に定評があります。',
      phone: '099-567-8901',
      website: 'https://example.com/reveil',
      established: '2015年',
      serviceArea: '鹿児島市・姶良市',
      features: ['女性設計士チーム', '水まわり設計に定評', 'インテリアコーディネート込み', '収納計画のプロ'],
    },
    points: ['女性設計士による繊細なデザイン', 'パウダールーム付きの広い洗面', 'ウォークスルークローゼット', 'カフェのようなキッチン空間', 'プライバシーに配慮した窓計画'],
    photos: ['/images/properties/15-photo-1.jpg', '/images/properties/15-photo-2.jpg', '/images/properties/15-photo-3.jpg'],
    designerMemo: {
      name: '松本 彩花',
      role: '女性設計士',
      comment: '女性ならではの視点で、毎日の暮らしが楽しくなる家を設計しました。パウダールーム付きの洗面やウォークスルークローゼットなど、身支度の動線にもこだわっています。キッチンはカフェのようなオープンスタイルで、料理の時間が楽しくなります。',
    },
  },
  {
    id: '16',
    title: '嘘だろ...これが平屋はヤバすぎる！',
    youtubeId: 'WzSTo2M9Mug',
    views: '47万回',
    price: '3,500万円',
    priceBreakdown: { building: '2,800万円', land: '450万円', misc: '250万円', perTsubo: '66.7万円' },
    layout: '4LDK',
    area: '42坪',
    landArea: '100坪',
    buildingCoverage: '50%',
    floorAreaRatio: '100%',
    terrain: '平坦地',
    roadAccess: '南東角地',
    zoning: '第一種低層住居専用地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'Panasonic', series: 'Lクラス' },
    bath: { maker: 'TOTO', size: '1624' },
    toilet: { maker: 'TOTO', series: 'ネオレストAH' },
    insulation: '等級6',
    uaValue: '0.43',
    earthquake: '等級3',
    builder: {
      name: 'グランドホーム鹿児島',
      location: '鹿児島県鹿児島市与次郎1-5-3',
      specialty: '大空間平屋',
      description: '「平屋の常識を変える」をテーマに、圧倒的なスケール感の平屋住宅を提案。大空間リビングやビルトインガレージなど、贅沢な暮らしを実現します。',
      phone: '099-678-9012',
      website: 'https://example.com/grand-home',
      established: '2000年',
      serviceArea: '鹿児島市・指宿市・南九州市',
      features: ['大空間設計', 'ビルトインガレージ対応', 'ホテルライク内装', '高級住宅実績多数'],
    },
    points: ['42坪の大空間LDK', '天井高4mの吹き抜け風リビング', 'ビルトインガレージ付き', '全室南向きの贅沢な間取り', 'ホテルライクなマスターベッドルーム'],
    photos: ['/images/properties/16-photo-1.jpg', '/images/properties/16-photo-2.jpg', '/images/properties/16-photo-3.jpg'],
    designerMemo: {
      name: '高橋 龍太郎',
      role: '設計部長',
      comment: '「平屋の常識を覆す」をコンセプトに、42坪の大空間を実現しました。天井高4mのリビングは、まるでホテルのロビーのような圧倒的な開放感。ビルトインガレージは雨の日の買い物にも便利で、実用性とデザインを両立させています。',
    },
  },
  {
    id: '17',
    title: '令和時代に超人気な間取りの平屋',
    youtubeId: '2KAwhfOO3uI',
    views: '47万回',
    price: '2,480万円',
    priceBreakdown: { building: '1,980万円', land: '350万円', misc: '150万円', perTsubo: '66万円' },
    layout: '3LDK',
    area: '30坪',
    landArea: '65坪',
    buildingCoverage: '60%',
    floorAreaRatio: '200%',
    terrain: '平坦地',
    roadAccess: '南側6m公道',
    zoning: '第一種住居地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'クリナップ', series: 'セントロ' },
    bath: { maker: 'Panasonic', size: '1616' },
    toilet: { maker: 'Panasonic', series: 'アラウーノS160' },
    insulation: '等級5',
    uaValue: '0.52',
    earthquake: '等級3',
    builder: {
      name: 'みらい住建',
      location: '鹿児島県霧島市国分中央3-12-7',
      specialty: '注文住宅・平屋',
      description: '霧島エリアを中心に、時代のトレンドを取り入れた注文住宅を提供。回遊動線やランドリールームなど、令和の暮らしに合った間取り提案が得意です。',
      phone: '0995-45-1234',
      website: 'https://example.com/mirai-juken',
      established: '2011年',
      serviceArea: '霧島市・姶良市・伊佐市',
      features: ['トレンド間取り提案', '回遊動線設計', '子育て世代応援', '地元密着型'],
    },
    points: ['令和の定番「回遊動線」を採用', 'ランドリールーム完備', 'リビング横の畳コーナー', 'ファミリークローゼット', 'スタディコーナー付き'],
    photos: ['/images/properties/17-photo-1.jpg', '/images/properties/17-photo-2.jpg', '/images/properties/17-photo-3.jpg'],
    designerMemo: {
      name: '井上 翔太',
      role: '設計担当',
      comment: '令和の子育て世代に人気の間取りを詰め込みました。回遊動線で家事のストレスを軽減し、ランドリールームで洗濯動線を完結。リビング横の畳コーナーはお子様の遊び場にも昼寝スペースにもなる万能空間です。',
    },
  },
  {
    id: '18',
    title: 'えっヤバすぎ！これはもはや平屋ではない。',
    youtubeId: 'P3walOjt0uE',
    views: '47万回',
    price: '3,800万円',
    priceBreakdown: { building: '3,000万円', land: '500万円', misc: '300万円', perTsubo: '66.7万円' },
    layout: '4LDK+S',
    area: '45坪',
    landArea: '110坪',
    buildingCoverage: '50%',
    floorAreaRatio: '100%',
    terrain: '平坦地',
    roadAccess: '南西角地',
    zoning: '第一種低層住居専用地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'LIXIL', series: 'リシェルSI' },
    bath: { maker: 'TOTO', size: '1624特注' },
    toilet: { maker: 'TOTO', series: 'ネオレストNX' },
    insulation: '等級6',
    uaValue: '0.38',
    earthquake: '等級3',
    builder: {
      name: '谷川建設',
      location: '長崎県長崎市松山町3-50',
      specialty: '木造住宅',
      description: '創業50年以上の老舗工務店。国産ひのきを使った木造住宅にこだわり、九州各地で高品質な住宅を提供。大規模な平屋から二世帯住宅まで幅広く対応。',
      phone: '095-123-4567',
      website: 'https://example.com/tanigawa',
      established: '1972年',
      serviceArea: '長崎県・佐賀県・福岡県',
      features: ['創業50年超の実績', '国産ひのき使用', '大規模住宅対応', '九州全域施工可能'],
    },
    points: ['平屋とは思えない圧倒的スケール', 'インナーガレージ2台分', '書斎+ワークスペース完備', 'プライベートテラス付き主寝室', '全館空調で年中快適'],
    photos: ['/images/properties/18-photo-1.jpg', '/images/properties/18-photo-2.jpg', '/images/properties/18-photo-3.jpg'],
    designerMemo: {
      name: '渡辺 裕介',
      role: '設計主任',
      comment: '国産ひのきの構造材で実現した大スパンの空間が最大の見どころです。インナーガレージ2台分を確保しながら、居住スペースも妥協なし。書斎とワークスペースは在宅勤務にも対応し、プライベートテラス付きの主寝室はまさに大人の隠れ家です。',
    },
  },
  {
    id: '19',
    title: '女性設計士の作るボーホーインテリアのかわいい平屋',
    youtubeId: 'npGkmEaOaI0',
    views: '44万回',
    price: '2,380万円',
    priceBreakdown: { building: '1,880万円', land: '350万円', misc: '150万円', perTsubo: '67.1万円' },
    layout: '3LDK',
    area: '28坪',
    landArea: '60坪',
    buildingCoverage: '60%',
    floorAreaRatio: '200%',
    terrain: '平坦地',
    roadAccess: '南側5m公道',
    zoning: '第一種住居地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'ウッドワン', series: 'スイージー' },
    bath: { maker: 'TOTO', size: '1616' },
    toilet: { maker: 'TOTO', series: 'ZJ2' },
    insulation: '等級5',
    uaValue: '0.54',
    earthquake: '等級3',
    builder: {
      name: 'ベガハウス',
      location: '鹿児島県鹿児島市上之園町24-1',
      specialty: 'デザイン住宅',
      description: '「暮らしに物語を」がモットー。自然素材とクラフト感あふれるデザインで、住む人の個性を引き出す住宅を提案。インテリアコーディネートまで一貫対応。',
      phone: '099-789-0123',
      website: 'https://example.com/vega-house',
      established: '2007年',
      serviceArea: '鹿児島市・姶良市・日置市',
      features: ['デザイン×自然素材', 'インテリアコーディネート一貫', 'オリジナル造作家具', 'SNS映えする空間設計'],
    },
    points: ['ボーホーインテリアの統一感', 'アーチ壁がアクセント', '無垢材フローリングの温もり', 'オープン棚のおしゃれ収納', '土間玄関からつながるシューズクローク'],
    photos: ['/images/properties/19-photo-1.jpg', '/images/properties/19-photo-2.jpg', '/images/properties/19-photo-3.jpg'],
    designerMemo: {
      name: '川口 美咲',
      role: 'インテリアデザイナー',
      comment: 'ボーホーインテリアの世界観を統一するため、素材選びから照明計画まで一貫してコーディネートしました。アーチ壁は空間にやわらかさを、無垢材フローリングは足触りの心地よさを演出。オープン棚は「見せる収納」で暮らしそのものがインテリアになります。',
    },
  },
  {
    id: '20',
    title: 'シンプルおしゃれの小さく可愛い平屋',
    youtubeId: 'crfgrlvsaWY',
    views: '40万回',
    price: '1,880万円',
    priceBreakdown: { building: '1,480万円', land: '280万円', misc: '120万円', perTsubo: '67.3万円' },
    layout: '2LDK',
    area: '22坪',
    landArea: '50坪',
    buildingCoverage: '60%',
    floorAreaRatio: '200%',
    terrain: '平坦地',
    roadAccess: '東側4m公道',
    zoning: '第一種住居地域',
    landCategory: '宅地',
    buildingCondition: 'なし',
    kitchen: { maker: 'LIXIL', series: 'シエラS' },
    bath: { maker: 'LIXIL', size: '1216' },
    toilet: { maker: 'LIXIL', series: 'ベーシア' },
    insulation: '等級4',
    uaValue: '0.60',
    earthquake: '等級3',
    builder: {
      name: '丸和建設',
      location: '鹿児島県霧島市隼人町見次1229',
      specialty: '注文住宅・平屋',
      description: '霧島エリアで40年以上の実績を持つ地元密着型工務店。シンプルで飽きのこないデザインと、コストパフォーマンスの高い家づくりが特徴です。',
      phone: '0995-42-5678',
      website: 'https://example.com/maruwa',
      established: '1983年',
      serviceArea: '霧島市・姶良市・曽於市',
      features: ['地元密着40年', 'コスパ重視の家づくり', 'シンプルデザイン', '若い世代の実績多数'],
    },
    points: ['22坪のコンパクトでも十分な広さ', 'シンプルな外観デザイン', 'LDK16帖の開放感', '造作洗面台がおしゃれ', 'ローコストでも妥協しない品質'],
    photos: ['/images/properties/20-photo-1.jpg', '/images/properties/20-photo-2.jpg', '/images/properties/20-photo-3.jpg'],
    designerMemo: {
      name: '木村 拓也',
      role: '設計担当',
      comment: 'シンプルでありながら飽きのこないデザインを心がけました。22坪でもLDK16帖の開放感を確保し、造作洗面台でオリジナリティをプラス。コストを抑えながらも品質に妥協しない、若いご夫婦にぴったりの住まいに仕上がりました。',
    },
  },
]

// Helper to get property by ID (returns first one as fallback)
export function getPropertyById(id: string): PropertyData {
  return properties.find(p => p.id === id) || properties[0]
}
